name: Add To GitHub Project

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    env:
      PROJECT_URL: ${{ vars.PROJECT_URL }}
      ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
    steps:
      - name: Add issue or pull request to project
        if: ${{ env.PROJECT_URL != '' && env.ADD_TO_PROJECT_PAT != '' }}
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: ${{ env.PROJECT_URL }}
          github-token: ${{ env.ADD_TO_PROJECT_PAT }}
